on: ["push", "pull_request"]
name: "Coveralls"

env:
      NODE_COVERALLS_DEBUG: 1
      TESTCOVERAGE_THRESHOLD: 0
      
jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: go test `go list ./... | grep -v e2e` -coverprofile coverage.out -covermode count
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov
      - name: Quality Gate - Test coverage shall be above threshold
        run: |
            echo "Quality Gate: checking test coverage is above threshold ..."
            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
                echo "OK"
            else
                echo "Failed"
                exit 1
            fi

