on: ["push", "pull_request"]
name: "Coveralls"

env:
  global:
    - COVERALLS_PARALLEL=true

jobs:
  coveralls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: go test `go list ./... | grep -v e2e` -coverprofile coverage_raw.out -covermode count
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          flag-name: run-$
          path-to-lcov: coverage.lcov
  finish:
    needs: test
    if: $
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "run-1,run-2"